# Fetching the minified node image on apline linux
FROM node:slim

# Setting up the work directory
WORKDIR /express-docker

# Copying all the files in our project
COPY . .

# Installing dependencies
RUN npm install

# Exposing server port
EXPOSE 7777

# Starting our application
CMD [ "npm", "run", "start" ]
